# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d21ed814910434196fb5ae8f96cb46d9f37f1506ea038e2c57bf5d6d19369ea840b539da8f8499b1621b6ae5a8f6c0802496429016c0e328cf595b675d80571a

test:
  secret_key_base: ece6cbebae7490cfaa391fc1c879e7db9bc8b1827d5cbf5092d245b6e87dbee5a53d20f58978b7585542a412caeef00862a76fd251286937267fc5117c606719

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
